Blur Effekt
PabloDeges/Rescuesine pull request #35
Opened 2024-07-04 08:33 UTC by PadellTech

Bei meinem Branch laesst sich das Buch in der Mobile Ansicht nichtmehr aufklappen. Ist das im Main branch auch der Fall?

2024-07-04 09:12 UTC, JohanTemme commented
Blur funktioniert bei mir nur auf den Roten filter button, alles weitere bleibt scharf.

2024-07-04 12:34 UTC, PabloDeges reviewed
funktioniert nicht wirklich, nur der filter button wird unscharf. Buch aufklappen klappt aber

2024-07-04 12:36 UTC, PabloDeges requested changes
ausßerdem lässt sich aus der mobile ansicht nicht mehr der login anzeigen.. button hat garkeine funktionalität mehr

2024-07-04 12:54 UTC, PadellTech commented
Danke euch. Ist behoben

2024-07-04 12:55 UTC, PadellTech commented
> ausßerdem lässt sich aus der mobile ansicht nicht mehr der login anzeigen.. button hat garkeine funktionalität mehr

Schaue ich mir momentan auch schon an

2024-07-04 13:10 UTC, PadellTech commented
Hamburger klappt wieder

2024-07-05 19:20 UTC, PaulSGE reviewed
Bei mir ist gar kein Blur.

2024-07-06 06:02 UTC, PadellTech commented
> Bei mir ist gar kein Blur.

Ach, hatte nicht alle Dateien commited. Jetzt aber wirklich 😅

2024-07-06 10:25 UTC, JohanTemme requested changes
Header Bar wird nicht geblurred, bitt noch ergänzen.
In der Mobile Ansicht funktioniert der Login-Button nicht.

2024-07-07 14:10 UTC, PabloDeges commented
> Header Bar wird nicht geblurred, bitt noch ergänzen.
> In der Mobile Ansicht funktioniert der Login-Button nicht.

Finde es eigentlich sogar ganz gut, dass die Headerbar nicht geblurred wird, wird ja auch nie von login überdeckt. 
Der Mobile Login sollte allerdings auf jeden Fall funktionieren

2024-07-08 10:13 UTC, merged